### PR TITLE
Add Sponge platform support

### LINKED ISSUE #230: Support Sponge platform (server and client)
https://github.com/SpongePowered/SpongeAPI

### PR DESCRIPTION
**Pull request by BlackBaroness**
Closes #230 

Hi, sorry for being super late!

Here is a Sponge 8 support (it's the latest stable API, included in all modern Sponge builds).

I added a `Player` argument, `Player` contextual and test `/tp <player> [player]` command. You can test it yourself using `./gradlew :examples:sponge:runServer`. I also wanted to add a `/gm` command, but Sponge has... special... API design and I couldn't understand how to make proper suggestions (but the parsing was relatively fine). However, I believe it's enough for this platform.

image

### CODE REVIEW

**Comment by BlackBaroness** [comment]
Fixed all merge and build issues

**Comment by Rollczi** [comment]
Hi @BlackBaroness, Thanks for your Pull Request!
Before checking the following code, I what to fix some issue with the git history in your branch.
image
As you can see, the commits do not match to the actual history.

We can fix this, but next time you will have to:
1. Update your fork repository. (see https://github.com/BlackBaroness/LiteCommands)
image
2. Fetch the latest commits from your fork repository (locally on your computer) 
image
3. Update master branch (locally on your computer) 
image
4. Create a new branch from the master branch. e.g. `feature/sponge-platform`
image

When you are done above, you can cherry-pick the commits from old branch.
Paste these commands in your terminal (in an open project)
`git checkout feature/sponge-platform`
`git cherry-pick 1de3114`
`git cherry-pick 016bc24`
`git cherry-pick 4834eac`
`git cherry-pick a9dad61`
`git cherry-pick 1485a7b`

In IntelliJ you can easily check the last commits (for master or other your branches) to verify them.
image

**Comment by BlackBaroness** [comment]
@Rollczi There is no problem with it actually, you can just squash my PR and only changed files will be changed (I checked it and there are only required ones, only sponge-related). It was my mistake, I didn't reset my branch so it's based on Instant support branch, not master. But since there are no merge conflicts and I removed all wrong changes, we can just merge. Squash will remove that history anyway

**Comment by vLuckyyy** [comment]
The history of your branch is very messed up, if you want this pull request to be merged, create a new branch and do ctrl + c and ctrl + v of your changes that add sponge, your code contains code that is not even on the master. Even though "THEORETICALLY" squash solves the issue, your pull request still has a damaged history. Come when you fix it!

this is an example of your damaged git history:

image

**Pull request closed without merging**
